name: linter-check

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  linter-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install depenpencies
        run: 
          pip install poetry
          pip install flake8
                
      - name: Run lint task
        run: make lint
