name: tests-and-linter-check

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  tests-and-linter-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install depenpencies
        run: 
          pip install poetry
          pip install flake8
          pip install pytest
          pip install pytest-cov
                
      - name: Run lint task
        run: make lint

      - name: Run tests
        run: poetry run pytest

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ac67632c32e62c0b31e6863520c469cc3a8a1487be0b914c527a05a6ddb3ab8d
        with:
          coverageCommand: make test-coverage
          debug: true
